spring.application.name=projeto-api-loguin

spring.datasource.username = root

spring.datasource.password = eduardo

spring.datasource.url = jdbc:mysql://localhost:3306/banco_de_usuarios?useTimezone=true&serverTimezone=UTC


